"""Add total_price field in cart model

Revision ID: 06f561609a82
Revises: e2e66aebe4a2
Create Date: 2025-05-14 13:13:30.616458

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06f561609a82'
down_revision = 'e2e66aebe4a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cart', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_price', sa.Float(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cart', schema=None) as batch_op:
        batch_op.drop_column('total_price')

    # ### end Alembic commands ###
