"""Update cart and cart_item models

Revision ID: 0bc7eeb40458
Revises: 08f101ed7963
Create Date: 2025-07-06 13:00:06.046390

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0bc7eeb40458'
down_revision = '08f101ed7963'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cart', schema=None) as batch_op:
        batch_op.alter_column('total_price',
               existing_type=mysql.FLOAT(),
               type_=sa.DECIMAL(precision=10, scale=2),
               existing_nullable=False)

    with op.batch_alter_table('cart_item', schema=None) as batch_op:
        batch_op.drop_column('price')
        batch_op.drop_column('total_price')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cart_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_price', mysql.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('price', mysql.FLOAT(), nullable=True))

    with op.batch_alter_table('cart', schema=None) as batch_op:
        batch_op.alter_column('total_price',
               existing_type=sa.DECIMAL(precision=10, scale=2),
               type_=mysql.FLOAT(),
               existing_nullable=False)

    # ### end Alembic commands ###
