"""Remove img and stock fields from product model

Revision ID: 4b2ec8c57b39
Revises: 8be93fba155e
Create Date: 2025-07-06 12:44:44.718084

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4b2ec8c57b39'
down_revision = '8be93fba155e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.drop_column('description')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', mysql.VARCHAR(length=100), nullable=True))

    # ### end Alembic commands ###
