"""Remove product, quantity from Cart table

Revision ID: 859ee9c079a4
Revises: b7cbef18f0ce
Create Date: 2025-05-14 14:24:57.529850

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '859ee9c079a4'
down_revision = 'b7cbef18f0ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cart', schema=None) as batch_op:
        batch_op.drop_constraint('cart_ibfk_1', type_='foreignkey')
        batch_op.drop_column('product_id')
        batch_op.drop_column('price')
        batch_op.drop_column('quantity')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cart', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quantity', mysql.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('price', mysql.FLOAT(), nullable=False))
        batch_op.add_column(sa.Column('product_id', mysql.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('cart_ibfk_1', 'product', ['product_id'], ['id'])

    # ### end Alembic commands ###
