"""Update order and order_item models

Revision ID: 08f101ed7963
Revises: 3c471062f2e6
Create Date: 2025-07-06 12:56:03.638238

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '08f101ed7963'
down_revision = '3c471062f2e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment_method', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.alter_column('total_price',
               existing_type=mysql.FLOAT(),
               type_=sa.DECIMAL(precision=10, scale=2),
               existing_nullable=False)
        batch_op.drop_column('order_date')

    with op.batch_alter_table('order_item', schema=None) as batch_op:
        batch_op.alter_column('price',
               existing_type=mysql.FLOAT(),
               type_=sa.DECIMAL(precision=10, scale=2),
               existing_nullable=True)
        batch_op.drop_column('total_price')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_price', mysql.FLOAT(), nullable=True))
        batch_op.alter_column('price',
               existing_type=sa.DECIMAL(precision=10, scale=2),
               type_=mysql.FLOAT(),
               existing_nullable=True)

    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('order_date', mysql.DATETIME(), nullable=True))
        batch_op.alter_column('total_price',
               existing_type=sa.DECIMAL(precision=10, scale=2),
               type_=mysql.FLOAT(),
               existing_nullable=False)
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')
        batch_op.drop_column('payment_method')

    # ### end Alembic commands ###
