"""Create orderItem table to separate order and orderitems and be able to order multiple items

Revision ID: ed417d921dd6
Revises: 859ee9c079a4
Create Date: 2025-05-14 14:36:10.206167

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ed417d921dd6'
down_revision = '859ee9c079a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('total_price', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['order.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('address_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint('order_ibfk_1', type_='foreignkey')
        batch_op.drop_constraint('order_ibfk_3', type_='foreignkey')
        batch_op.create_foreign_key(None, 'address', ['address_id'], ['id'])
        batch_op.drop_column('address')
        batch_op.drop_column('product_id')
        batch_op.drop_column('quantity')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quantity', mysql.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('product_id', mysql.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('address', mysql.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('order_ibfk_3', 'address', ['address'], ['id'])
        batch_op.create_foreign_key('order_ibfk_1', 'product', ['product_id'], ['id'])
        batch_op.drop_column('address_id')

    op.drop_table('order_item')
    # ### end Alembic commands ###
